package sys.modelo;
// Generated 16-sep-2023 10:27:05 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codUsu;
     private String nombreUsuario;
     private String password;

    public Usuario() {
    }

    public Usuario(int codUsu, String nombreUsuario, String password) {
       this.codUsu = codUsu;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
    }
   
    public int getCodUsu() {
        return this.codUsu;
    }
    
    public void setCodUsu(int codUsu) {
        this.codUsu = codUsu;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


